### ISSUE TITLE
Front end Corrections

### ISSUE THREAD

**Issue by chalanadulajdilshan** [chalanadulajdilshan/grade#7]

**Comment by hansajith18** [comment]
about.html
 courses_list.html
 me page eka

![a77b495c-9033-437a-9948-5eca6010373e](https://user-images.githubusercontent.com/59231358/158723609-ad406ced-42b5-41bb-9317-772586b2829c.jpg)
 gride version eka enna ona

 courses_details.html

![16c5d5e6-6b37-4d4b-9514-88053469ee64](https://user-images.githubusercontent.com/59231358/158723656-99bb1bc6-76e2-499c-bc99-2205d7490f19.jpg)

 contact_us.html
 faqs.html
 blog_grid_3.html
 blog_single_image_post.html
